services:
  postgis:
    image: postgis/postgis:14-3.4-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - postgis-data:/var/lib/postgresql/data

volumes:
  postgis-data: